# Use the Kaggle Python image as the base image
# for CPU
FROM gcr.io/kaggle-images/python
# for GPU
# FROM gcr.io/kaggle-gpu-images/python:

# Install an additional package using pip. Replace 'your-package' with the actual package name.
RUN pip install pygame


